name: slack-notification-action
description: notify the current workflow run to a Slack channel

inputs:
  slack-channel-id:
    description: ID of the Slack channel
    required: true
  slack-app-token:
    description: Slack App Bot Token
    required: true
  github-token:
    description: GitHub token (optional)
    required: true
    default: ${{ github.token }}

outputs:
  annotation-failure-messages:
    description: annotation messages of failure in the workflow run
    value: ${{ steps.summary.outputs.annotation-failure-messages }}
  pull-request-number:
    description: associated pull request number, if exists
    value: ${{ steps.summary.outputs.pull-request-number }}
  payload:
    description: JSON payload
    value: ${{ steps.payload.outputs.result }}

runs:
  using: composite
  steps:
    - uses: int128/workflow-run-summary-action@v1
      id: summary
      with:
        token: ${{ inputs.github-token }}

    - uses: actions/github-script@v6
      id: payload
      env:
        bodyHeader: |-
          @${{ github.actor }} check the ${{ github.event.workflow_run.conclusion }}
        bodyMessage: |-
          ${{ steps.summary.outputs.annotation-failure-messages }}
        contextBranch: |-
          ${{ github.repository }}/*${{ github.event.workflow_run.head_branch }}*
        contextPullRequest: |-
          <${{ steps.summary.outputs.pull-request-url }}|#${{ steps.summary.outputs.pull-request-number }}>
        contextWorkflow: |-
          workflow: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow_run.name }}>
      with:
        # preview on https://app.slack.com/block-kit-builder
        script: |
          return {
            blocks: [
              {
                type: "section",
                text: {
                  type: "mrkdwn",
                  text: (() => {
                    if (process.env.bodyMessage) {
                      return [process.env.bodyHeader, '```', process.env.bodyMessage, '```'].join('\n')
                    }
                    return process.env.bodyHeader
                  })()
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": process.env.contextBranch
                  },
                  {
                    "type": "mrkdwn",
                    "text": process.env.contextPullRequest
                  },
                  {
                    "type": "mrkdwn",
                    "text": process.env.contextWorkflow
                  }
                ]
              }
            ]
          }

    # Don't notify if conclusion is cancelled or skipped.
    # Skip if Slack App token is not set such as test workflow.
    - if: |
        steps.summary.outputs.cancelled != 'true' &&
        steps.summary.outputs.skipped != 'true' &&
        inputs.slack-app-token
      uses: slackapi/slack-github-action@v1
      with:
        channel-id: ${{ inputs.slack-channel-id }}
        payload: ${{ steps.payload.outputs.result }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-app-token }}
