name: slack-notification-action
description: Notify the current workflow run to a Slack channel

inputs:
  slack-channel-id:
    description: ID of the Slack channel
    required: true
  slack-thread-ts:
    description: Thread timestamp to post message in
    required: false
  slack-app-token:
    description: Bot token of Slack App. If not set, dry run is performed
    required: false
  github-token:
    description: GitHub token (optional)
    required: true
    default: ${{ github.token }}
  github-job-status:
    default: ${{ job.status }}
    description: The current status of the job. Possible values are success, failure, or cancelled.
    deprecationMessage: Do not set github-job-status. Keep the default value.

  mention-message:
    description: Message to mention the current user. Set to empty to disable mentioning.
    required: false
    default: |-
      @${{ github.actor }}

runs:
  using: 'node20'
  main: 'dist/index.js'
