name: slack-notification-action
description: Notify the current workflow run to a Slack channel

inputs:
  slack-channel-id:
    description: ID of the Slack channel
    required: true
  slack-app-token:
    description: Bot token of Slack App
    required: true
  github-token:
    description: GitHub token (optional)
    required: true
    default: ${{ github.token }}
  github-job-status:
    default: ${{ job.status }}
    description: The current status of the job. Possible values are success, failure, or cancelled.
    deprecationMessage: Do not set github-job-status. Keep the default value.

  lost-communication-error-message:
    description: Message to send when "The self-hosted runner lost communication with the server" error
    required: true
    default: The job was failed due to an infrastructure problem. Please rerun it if needed.

runs:
  using: 'node20'
  main: 'dist/index.js'
