name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build
      - uses: int128/release-typescript-action@53849724823ecc30b2480305fd517145b873caad # v1.79.0
        with:
          major-version: 2
