name: test

on:
  pull_request:
    paths:
      - action.yaml
      - .github/workflows/test.yaml
  push:
    branches:
      - v1
    paths:
      - action.yaml
      - .github/workflows/test.yaml

jobs:
  smoke-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This does not send a payload actually
      - name: Run quipper/slack-notification-action
        uses: ./
        with:
          slack-channel-id: ABCDEF123
          slack-app-token: ${{ secrets.SLACK_APP_TOKEN }}
