name: test

on:
  pull_request:
    paths:
      - action.yaml
      - .github/workflows/example.yaml

jobs:
  send:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          slack-channel-id: ABCDEF123 # your Slack channel
          slack-app-token: ${{ secrets.SLACK_APP_TOKEN }}
        # for testing on pull request
        continue-on-error: true
