name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - graphql-codegen.*
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - graphql-codegen.*
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - name: Run quipper/slack-notification-action
        uses: ./
        with:
          slack-channel-id: ABCDEF123

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm run check --fix
      - run: pnpm graphql-codegen
      - uses: int128/update-generated-files-action@ffeee0fc8e9dc4718c1f36be68b9d89b2be28e51 # v2.109.0

  fixture:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo '::error::This is a fixture error.'
